DROP TABLE IF EXISTS ipam_aggregate CASCADE;
DROP TABLE IF EXISTS ipam_ipaddress CASCADE;
DROP TABLE IF EXISTS ipam_prefix CASCADE;
DROP TABLE IF EXISTS ipam_rir CASCADE;
DROP TABLE IF EXISTS ipam_role CASCADE;
DROP TABLE IF EXISTS ipam_service CASCADE;
DROP TABLE IF EXISTS ipam_service_ipaddresses CASCADE;
DROP TABLE IF EXISTS ipam_vlan CASCADE;
DROP TABLE IF EXISTS ipam_vlangroup CASCADE;
DROP TABLE IF EXISTS ipam_vrf CASCADE;
DROP TABLE IF EXISTS tenancy_tenant CASCADE;
DROP TABLE IF EXISTS tenancy_tenantgroup CASCADE;

DROP SEQUENCE IF EXISTS ipam_aggregate_id_seq;
DROP SEQUENCE IF EXISTS ipam_ipaddress_id_seq;
DROP SEQUENCE IF EXISTS ipam_prefix_id_seq;
DROP SEQUENCE IF EXISTS ipam_rir_id_seq;
DROP SEQUENCE IF EXISTS ipam_role_id_seq;
DROP SEQUENCE IF EXISTS ipam_service_id_seq;
DROP SEQUENCE IF EXISTS ipam_service_ipaddresses_id_seq;
DROP SEQUENCE IF EXISTS ipam_vlan_id_seq;
DROP SEQUENCE IF EXISTS ipam_vlangroup_id_seq;
DROP SEQUENCE IF EXISTS ipam_vrf_id_seq;
DROP SEQUENCE IF EXISTS tenancy_tenant_id_seq;
DROP SEQUENCE IF EXISTS tenancy_tenantgroup_id_seq;
