docker:
  image: docker:20.10.5
  services:
  - docker:20.10.5-dind

  before_script:
  - apk add make
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

  script:
  - make SUFFIX=ci-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA} GITLAB_AUTHN=gitlab-ci-token:${CI_JOB_TOKEN} manifest install

  artifacts:
    paths:
      - config
      - deploy/*.yaml
