docker:
  image: docker:20.10.5
  services:
  - docker:20.10.5-dind

  before_script:
  - |
    if [ -n "${CI_COMMIT_TAG}" ] ; then
      # If this build is from a git tag, use that as the docker tag.
      export TAG_SPECIFIC="${CI_COMMIT_TAG}"
    else
      # If this build is from a branch, use the name and sha as the
      # docker tag.
      export TAG_SPECIFIC="${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
    fi
  - apk add make
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

  script:
  - make SUFFIX=${TAG_SPECIFIC} GITLAB_AUTHN=gitlab-ci-token:${CI_JOB_TOKEN} manifest install

  artifacts:
    paths:
      - config
      - deploy/*.yaml
