---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: epic
  name: web-service
  namespace: epic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: epic
  name: web-service
rules:
- apiGroups:
  - epic.acnodal.io
  resources:
  - accounts
  - lbservicegroups
  - serviceprefixes
  - loadbalancers
  - remoteendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - epic.acnodal.io
  resources:
  - loadbalancers
  - remoteendpoints
  verbs:
  - create
  - update
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: epic
  name: web-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: web-service
subjects:
- kind: ServiceAccount
  name: web-service
  namespace: epic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: epic
    component: web-service
  name: web-service
  namespace: epic
spec:
  selector:
    matchLabels:
      app: epic
      component: web-service
  template:
    metadata:
      labels:
        app: epic
        component: web-service
    spec:
      containers:
      - name: web-service
        image: registry.gitlab.com/acnodal/epic/web-service:unknown
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: true
      imagePullSecrets:
      - name: gitlab
      serviceAccountName: web-service
      terminationGracePeriodSeconds: 0
---
kind: Service
apiVersion: v1
metadata:
  name: web-service
  namespace: epic
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
    name: ws
  selector:
    app: epic
    component: web-service
