name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with: {submodules: recursive}

    - uses: actions/setup-go@v4
      with: {go-version: '=1.19.8'}

    - name: Decide what we're going to call this
      run: |
        TAG_SPECIFIC=${{ github.ref_name }}
        # if we're building from a branch (i.e., not a tag) then add
        # the short sha so we can have more than one build per branch
        if [[ ${{ github.ref }} != refs/tags/* ]]; then
          TAG_SPECIFIC=${TAG_SPECIFIC}-$(git rev-parse --short HEAD)
        fi
        echo $TAG_SPECIFIC
        echo "TAG_SPECIFIC=$TAG_SPECIFIC" >> $GITHUB_ENV

    - name: Make
      run: |
        make SUFFIX=${TAG_SPECIFIC} test docker-build

    - name: Push
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        docker login -u epic-gateway+github_actions -p ${{ secrets.QUAY_EPIC_GATEWAY }} quay.io
        make SUFFIX=${TAG_SPECIFIC} docker-push
